spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@[your_ip]:27017/vaultdemo
management:
  endpoint:
    refresh:
      enabled: true
    restart:
      enabled: true